theme_bg="#fbf1c7"
theme_blue="#458588"
theme_yellow="#d79921"
theme_red="#cc241d"
theme_white="#3c3836"
theme_green="#98971a"
theme_gray="#ebdbb2"
theme_gray_light="#928374"

# Message such as "(rename-window) vim"
set -g message-style bg=$theme_bg,fg=$theme_green
set -g message-command-style bg=$theme_bg,fg=$theme_green

# Global status bar
set -g status-bg $theme_gray
set -g status-fg $theme_white

# Set buffer tab styles
set-option -g window-status-format "#[fg=$theme_bg,bg=$theme_bg,nobold,nounderscore,noitalics]#[fg=$theme_white,bg=$theme_gray] [#I] #W #[fg=$theme_bg,bg=$theme_bg,nobold,nounderscore,noitalics]"
set-option -g window-status-current-format "#[fg=$theme_bg,bg=$theme_gray,nobold,nounderscore,noitalics]#[fg=$theme_bg,bg=$theme_green,nobold] [#I] #W #[fg=$theme_gray,bg=$theme_bg,nobold,nounderscore,noitalics]"
