theme_bg="#141415"
theme_blue="#6e94b2"
theme_yellow="#f3be7c"
theme_red="#d8647e"
theme_white="#cdcdcd"
theme_green="#7fa563"
theme_gray="#252530"
theme_gray_light="#606079"

# Message such as "(rename-window) vim"
set -g message-style bg=$theme_bg,fg=$theme_green
set -g message-command-style bg=$theme_bg,fg=$theme_green

# Global status bar
set -g status-bg $theme_gray
set -g status-fg $theme_white

# Set buffer tab styles
set-option -g window-status-format "#[fg=$theme_bg,bg=$theme_bg,nobold,nounderscore,noitalics]#[fg=$theme_white,bg=$theme_gray] [#I] #W #[fg=$theme_bg,bg=$theme_bg,nobold,nounderscore,noitalics]"
set-option -g window-status-current-format "#[fg=$theme_bg,bg=$theme_gray,nobold,nounderscore,noitalics]#[fg=$theme_bg,bg=$theme_green,nobold] [#I] #W #[fg=$theme_gray,bg=$theme_bg,nobold,nounderscore,noitalics]"
